### ISSUE TITLE
can not find corrent files

### ISSUE THREAD

**Issue by wzu0** [russdill/bch_verilog#6]
Hello, thank you for sharing. I'm a graduate student from Wenzhou University. In order to create a project, I encountered some problems when importing the design resources you shared. The problem is as follows: when importing xilinx_ decoder(one file from your shared files), you will be asked to add "u_ pipeline:xil_ defaultlib.pipeline" this file,but I did not find this file in the folder you shared.Besides，when you add the file"bch_syndrome(one file in you BCH files)", you will be asked to add other files that do not exist in your file in the sub file folder. The development platform I use is vivado 2019.3 .
![捕获](https://user-images.githubusercontent.com/90365638/132806553-427adbba-8dd2-4a8d-b35b-ebb15148a35a.PNG)

**Comment by russdill** [comment]
The error message you included is using a fake (and thus missing) symbol
name to indicate a configuration error. You've set the PIPELINE_STAGES
parameter to a value greater than 2, which isn't supported by that module

**Comment by wzu0** [comment]
Thank you for your generous answer, so what should I do to solve the problem?

**Comment by russdill** [comment]
Don't configure the PIPELINE_STAGES parameter for that module to a value larger than 2....
